apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: cowboys
spec:
  latestResourceSchemas:
  - today.cowboys.wildwest.dev
  permissionClaims:
  - group: ""
    resource: configmaps
    all: true
