name: Build and publish mkdocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name kcp-ci-bot
          git config user.email no-reply@kcp.io

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material mkdocs-macros-plugin mkdocs-awesome-pages-plugin mkdocs-static-i18n

      - run: cd website && mkdocs gh-deploy --force
