apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v250312-8223e7b.applications.apis.contrib.kcp.io
spec:
  group: apis.contrib.kcp.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      description: Application is the Schema for the applications API.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: ApplicationSpec defines the desired state of Application.
          properties:
            databaseRef:
              description: |-
                INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file
              type: string
            databaseSecretRef:
              description: |-
                SecretReference represents a Secret Reference. It has enough information to retrieve secret
                in any namespace
              properties:
                name:
                  description: name is unique within a namespace to reference a secret
                    resource.
                  type: string
                namespace:
                  description: namespace defines the space within which the secret
                    name must be unique.
                  type: string
              type: object
              x-kubernetes-map-type: atomic
          type: object
        status:
          description: ApplicationStatus defines the observed state of Application.
          properties:
            connectionString:
              type: string
            status:
              type: string
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
