apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:faros:ml-training-workspacetype-use
rules:
- apiGroups: ["tenancy.kcp.io"]
  resources:
  - "workspacetypes"
  resourceNames:
  - "ml-training"
  verbs: ["use"]
