apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:faros-ml:authenticated:apiexport:kcp-admin:maximal-permission-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:faros-ml:apiexport:kcp-admin:maximal-permission-policy
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: apis.kcp.io:binding:system:kcp:admin
