apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:faros:authenticated:training-workspacetype-use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:faros:training-workspacetype-use
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
