apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: publish-cnpg-database
spec:
  resource:
    kind: Database
    apiGroup: postgresql.cnpg.io
    version: v1
  naming:
    # This is the implicit default configuration.
    namespace: "$remoteClusterName"
    name: "$remoteName"