apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubeconfig-admin
spec:
  username: admin@kcp.io
  groups:
    - kcp-admin
  validity: 8766h
  secretRef:
    name: admin-kubeconfig
  target:
    frontProxyRef:
      name: frontproxy
