apiVersion: operator.kcp.io/v1alpha1
kind: FrontProxy
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: frontproxy
spec:
  rootShard:
    ref:
      name: root
  externalHostname: kcp.localhost
