apiVersion: apis.contrib.kcp.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: crd
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  databaseRef: db-one
  databaseSecretRef:
    name: kcp-superuser
